[package]
name = "usql-migrate"
version = "0.1.0"
edition = "2024"

[dependencies]
usql-core = { path = "../usql-core" }
usql-builder = { path = "../usql-builder" }
usql-value = { path = "../usql-value" }
futures-core = { version = "0.3" }
