[package]
name = "usql-migrate"
version = "0.1.0"
edition = "2024"

[dependencies]
usql-core = { path = "../usql-core", features = ["std"] }
usql-builder = { path = "../usql-builder" }

futures-core = { version = "0.3" }
